popular_langs = ['C',
                'C#',
                'C++',
                'CoffeeScript',
                'CSS',
                'Dart',
                'DM',
                'Elixir',
                'Go',
                'Groovy',
                'HTML',
                'Java',
                'JavaScript',
                'Kotlin',
                'Objective-C',
                'Perl',
                'PHP',
                'PowerShell',
                'Python',
                'Ruby',
                'Rust',
                'Scala',
                'Shell',
                'Swift',
                'TypeScript']


other_langs = ['Jupyter Notebook',
            'R',
            'TeX',
            'Max',
            'Haskell',
            'OCaml',
            'Fortran',
            'MATLAB'
            ]